/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Metodo;

import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.math.plot.Plot2DPanel;

/**
 *
 * @author dariorobertho
 */
public class Promedio extends javax.swing.JFrame {

   
    public Promedio() {
       // DefaultTableModel modelo = new DefaultTableModel();
        initComponents();
        grafica.setBounds(10, 200, 350, 250);
        add(grafica);
        grafica.setVisible(false);
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cmd_generar = new javax.swing.JButton();
        lbl_texto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_eventos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmb_opciones = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        data_datos = new javax.swing.JTable();
        cmd_nuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cmd_generar.setText("Generar");
        cmd_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_generarActionPerformed(evt);
            }
        });

        lbl_texto.setText("Promedio movil");

        jLabel2.setText("Numero de eventos");

        jLabel3.setText("Promedio");

        cmb_opciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bimensual", "Trimestral", "Cuatrimestral", "Semestral", "Anual" }));

        data_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Evento", "Valor", "Promedio", "Diferencia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(data_datos);

        cmd_nuevo.setText("Nuevo");
        cmd_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_nuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_eventos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmd_generar))
                            .addComponent(cmb_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_nuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_texto)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_eventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmd_generar)
                            .addComponent(jLabel2)
                            .addComponent(cmd_nuevo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmb_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(this.cmb_opciones.getSelectedItem() == "Bimensual"){
            CalcularPromedio(2,"Bimensual");
        } else if(this.cmb_opciones.getSelectedItem() =="Trimestral"){
            CalcularPromedio(3, "Trimestral");
        }else if(this.cmb_opciones.getSelectedItem() =="Cuatrimestral"){
            CalcularPromedio(4, "Cuatrimestral");
        }else if(this.cmb_opciones.getSelectedItem() =="Semestral"){
            CalcularPromedio(6, "Semestral");
        }else if(this.cmb_opciones.getSelectedItem() =="Anual"){
            CalcularPromedio(12, "Anual");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed
    public void CalcularPromedio(int numero, String tipo){
        int tiempo = this.data_datos.getRowCount();
        //JOptionPane.showMessageDialog(rootPane, tiempo);
        double evento = 0, valor = 0, promedio = 0, diferencia = 0;
        //String mensaje = "";
        if(numero <= (tiempo-1)){
            for (int i = 0; i <= tiempo-1; i++)
			{
			this.data_datos.setValueAt("", i, 2);
                        this.data_datos.setValueAt("", i, 3);
                        //this.data_datos.setValueAt("", i, 4);
			}
            for (int i = numero; i <tiempo; i++){
				for (int j = 1; j <numero+1; j++)
				{
                                    String dato1 = (String) (this.data_datos.getValueAt(i-j, 1));
                                    
                                    dato1=dato1.replaceAll(",", ".");
                                    evento += Double.parseDouble(dato1);
					//valor += Convert::ToDouble(this->dataGridView1->Rows[i - j]->Cells[1]->Value);
				}
				promedio = evento / numero;
				if (this.data_datos.getValueAt(i, 1) != "")
				{
                                    String dato1 = (String) (this.data_datos.getValueAt(i, 1));
                                    dato1 = dato1.replaceAll(",", ".");
                                    valor = Double.parseDouble(dato1);
					// valor = Convert::ToDouble(this->dataGridView1->Rows[i]->Cells[1]->Value);
				}
				
				diferencia = valor - promedio;
                                DecimalFormat decimales = new DecimalFormat("0.00");  
                                this.data_datos.setValueAt(""+decimales.format(promedio)+"", i, 2);
                                this.data_datos.setValueAt(""+decimales.format(diferencia)+"", i, 3);
                                
				evento = 0;
				valor = 0;
			}
			//Graficar();
                                 //para generar primera gráfica
                         double [] x1 = new double[tiempo-1];
                         double [] y1 = new double[tiempo-1];
                         for (int i = 0; i <tiempo-1; i++){
                           x1[i] = i+1;
                           String datoy = (String) (this.data_datos.getValueAt(i, 1));  
                           datoy = datoy.replaceAll(",", ".");
                           y1[i] = Double.parseDouble(datoy);
                         }
                            //dibujar primera
                            grafica.setVisible(true);
                            grafica.addLegend("SOUTH");
                            grafica.removeAllPlots();
                            grafica.addLinePlot("Valores reales",Color.GREEN, x1,y1);
                              //generar segunda grafica
                             double [] x2 = new double[tiempo-numero];
                             double [] y2 = new double[tiempo-numero];
                             int z = tiempo-numero;
                             int c = tiempo-z;
                               for(int j=0;j<z;j++){
                                 x2[j] = c+(j+1) ;
                                 String datoy2 = (String) (this.data_datos.getValueAt(c+j, 2));
                                 datoy2 = datoy2.replaceAll(",", ".");
                                 y2[j] = Double.parseDouble(datoy2);
                               }
                                 //dibujar grafica
                                  grafica.addLinePlot("Promedio",Color.RED, x2,y2);        
            
		} else{
            JOptionPane.showMessageDialog(rootPane, "Para calcular el promedio " + tipo + " se deben generar mínimo " + numero + " eventos");
            limpiar();
        }
        
        
        
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    //funcion para limpiar elementos
    public void limpiar(){
        txt_eventos.setText("");
        limpiargrilla();
        cmd_generar.setEnabled(true);
        grafica.setVisible(false);
        txt_eventos.requestFocus();
        cmb_opciones.setSelectedItem("Bimensual");
        
    }
    
    public void limpiargrilla(){
        DefaultTableModel tabla;
            tabla = (DefaultTableModel) this.data_datos.getModel();
            int a =tabla.getRowCount();
            for(int i=0; i<a; i++)
                tabla.removeRow(0);
    }
    
    
    private void cmd_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_generarActionPerformed
        // TODO add your handling code here:
        
        int x = Integer.parseInt(txt_eventos.getText());
        if (x <= 0){
            JOptionPane.showMessageDialog(txt_eventos, "El número debe ser mayor a 0");
        } else{
           if(this.data_datos.getRowCount() > 0){
               this.data_datos.setModel(new DefaultTableModel());
           }
        }
      for(int i=1;i<x+2;i++){
             if(i==(x+1)){
                 ((DefaultTableModel) data_datos.getModel()).addRow(new Object[]{"","0"});
                 
                 
             } else{
                 
                 ((DefaultTableModel) data_datos.getModel()).addRow(new Object[]{i});
             }
      }
           cmd_generar.setEnabled(false);
        
    }//GEN-LAST:event_cmd_generarActionPerformed

    private void cmd_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_nuevoActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_cmd_nuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Promedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Promedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Promedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Promedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Promedio().setVisible(true);
            }
        });
    }    
Plot2DPanel grafica = new Plot2DPanel();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmb_opciones;
    private javax.swing.JButton cmd_generar;
    private javax.swing.JButton cmd_nuevo;
    private javax.swing.JTable data_datos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_texto;
    private javax.swing.JTextField txt_eventos;
    // End of variables declaration//GEN-END:variables
}
